import type { AppSettings } from "./types";

export const DEFAULT_SETTINGS: Required<AppSettings> = {
  MAX_STRING_LENGTH: 15,
  MAX_NOTE_LENGTH: 400,
  MAX_SEARCH_LENGTH: 100,
  MAX_INT_INPUT: 9999,
  MAX_AGE: 120,
  MAX_ROOM_CAPACITY: 999,
  ID_NUMBER_LENGTH: 9,
  MAX_TAG_LENGTH: 30,
  MAX_TAGS_PER_FIELD: 20,
  MAX_PHONE_LENGTH: 10,
  DATE_PAST_YEARS: 119,
  DATE_FUTURE_YEARS: 10,
  GRADE_FIRST_AGE: 6,
  GRADE_ADULT_AGE: 18,
  DEFAULT_AGE_MIN: 5,
  DEFAULT_AGE_MAX: 18,
  CLASS_NEAR_FULL_THRESHOLD: 0.8,
};
